/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/base/AppSidebar.vue')['default']
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseLoader: typeof import('./src/components/base/loader/BaseLoader.vue')['default']
    BaseModal: typeof import('./src/components/base/modal/BaseModal.vue')['default']
    BaseStub: typeof import('./src/components/base/stub/BaseStub.vue')['default']
    BaseTag: typeof import('./src/components/base/tag/BaseTag.vue')['default']
    BoardCard: typeof import('./src/components/board/boardCard/BoardCard.vue')['default']
    CreateBoardModal: typeof import('./src/components/modals/CreateBoardModal.vue')['default']
    CreateTaskModal: typeof import('./src/components/modals/CreateTaskModal.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stub: typeof import('./src/components/base/stub/Stub.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const AppSidebar: typeof import('./src/components/base/AppSidebar.vue')['default']
  const BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
  const BaseLoader: typeof import('./src/components/base/loader/BaseLoader.vue')['default']
  const BaseModal: typeof import('./src/components/base/modal/BaseModal.vue')['default']
  const BaseStub: typeof import('./src/components/base/stub/BaseStub.vue')['default']
  const BaseTag: typeof import('./src/components/base/tag/BaseTag.vue')['default']
  const BoardCard: typeof import('./src/components/board/boardCard/BoardCard.vue')['default']
  const CreateBoardModal: typeof import('./src/components/modals/CreateBoardModal.vue')['default']
  const CreateTaskModal: typeof import('./src/components/modals/CreateTaskModal.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElResult: typeof import('element-plus/es')['ElResult']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Stub: typeof import('./src/components/base/stub/Stub.vue')['default']
}