/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/base/header/AppHeader.vue')['default']
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseContextMenu: typeof import('./src/components/base/contextMenu/BaseContextMenu.vue')['default']
    BaseInlineEdit: typeof import('./src/components/base/inlineEdit/BaseInlineEdit.vue')['default']
    BaseLoader: typeof import('./src/components/base/loader/BaseLoader.vue')['default']
    BaseModal: typeof import('./src/components/base/modal/BaseModal.vue')['default']
    BaseStub: typeof import('./src/components/base/stub/BaseStub.vue')['default']
    BaseTag: typeof import('./src/components/base/tag/BaseTag.vue')['default']
    CreateColumnModal: typeof import('./src/components/modals/CreateColumnModal.vue')['default']
    CreateProjectModal: typeof import('./src/components/modals/CreateProjectModal.vue')['default']
    CreateTaskModal: typeof import('./src/components/modals/CreateTaskModal.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ProjectBoard: typeof import('./src/components/project/projectBoard/ProjectBoard.vue')['default']
    ProjectCard: typeof import('./src/components/project/projectCard/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsInput: typeof import('./src/components/base/tagsInput/TagsInput.vue')['default']
    TaskCard: typeof import('./src/components/project/taskCard/TaskCard.vue')['default']
    TaskDrawer: typeof import('./src/components/project/taskDrawer/TaskDrawer.vue')['default']
    ThemeToggle: typeof import('./src/components/base/themeToggle/ThemeToggle.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const AppHeader: typeof import('./src/components/base/header/AppHeader.vue')['default']
  const BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
  const BaseContextMenu: typeof import('./src/components/base/contextMenu/BaseContextMenu.vue')['default']
  const BaseInlineEdit: typeof import('./src/components/base/inlineEdit/BaseInlineEdit.vue')['default']
  const BaseLoader: typeof import('./src/components/base/loader/BaseLoader.vue')['default']
  const BaseModal: typeof import('./src/components/base/modal/BaseModal.vue')['default']
  const BaseStub: typeof import('./src/components/base/stub/BaseStub.vue')['default']
  const BaseTag: typeof import('./src/components/base/tag/BaseTag.vue')['default']
  const CreateColumnModal: typeof import('./src/components/modals/CreateColumnModal.vue')['default']
  const CreateProjectModal: typeof import('./src/components/modals/CreateProjectModal.vue')['default']
  const CreateTaskModal: typeof import('./src/components/modals/CreateTaskModal.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ProjectBoard: typeof import('./src/components/project/projectBoard/ProjectBoard.vue')['default']
  const ProjectCard: typeof import('./src/components/project/projectCard/ProjectCard.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TagsInput: typeof import('./src/components/base/tagsInput/TagsInput.vue')['default']
  const TaskCard: typeof import('./src/components/project/taskCard/TaskCard.vue')['default']
  const TaskDrawer: typeof import('./src/components/project/taskDrawer/TaskDrawer.vue')['default']
  const ThemeToggle: typeof import('./src/components/base/themeToggle/ThemeToggle.vue')['default']
}